- resources/lib/addonworker.py
- resources/lib/listitem.py
> Adding context menu of kinopub comments

- src/resources/lib/plugin.py
поломан путь в раздел ТВ шоу в версии 2.8.0
> fix broken link to tv shows

- src/resources/lib/utils.py
Я не проверял всех возможных последствий, не знаю с какой целью там очищались данные, но с этим фиксом плейлисты работают
> #61 fix crash on playing multiple items

- .pre-commit-config.yaml
- src/resources/lib/auth.py
- src/resources/lib/client.py
- src/resources/lib/listitem.py
- src/resources/lib/logger.py
- src/resources/lib/main.py
- src/resources/lib/player.py
- src/resources/lib/plugin.py
- src/resources/lib/routing.py
- src/resources/lib/settings.py
- src/resources/lib/utils.py
Monkey port for Kodi 19 via 2to3 tool and manual error messages fix. 
With .pre-commit-config.yaml fixes
> kodi 19 py3 port

- src/resources/lib/listitem.py
- src/resources/lib/routing.py
"Will not watch" menu item was not working.
> Fix "Will not watch" functionality for the TV Series.

- src/resources/lib/main.py
> pluralize containers content type

- src/resources/lib/main.py
Fixes quarckster/kodi.kino.pub#89
> fix fail when render 3d items in watching section

- src/resources/lib/main.py
@quarckster you changed by mistake back to movie :)
> changing back content_type_map for all to tvshow

- src/resources/lib/main.py
> Fixed trailers urls

- src/resources/lib/main.py
- src/resources/lib/modeling.py
- src/resources/settings.xml
> add exclude anime feature

- src/resources/lib/modeling.py
> Added thumbnail images from small posters

- src/resources/lib/auth.py
> Fixed 429 status code error handling in authentication module

- src/resources/lib/auth.py
> Fixed UnboundLocalError in auth request

- src/resources/lib/modeling.py
> Added iconImage and thumbnailImage into playable list item

- src/resources/lib/main.py
> Fixed search

- src/resources/lib/client.py
- src/resources/lib/listitem.py
- src/resources/lib/modeling.py
- src/resources/lib/utils.py
> Fix toggle watched

- src/resources/lib/modeling.py
> Fixed missing 'Буду смотреть' context menu item

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- src/resources/lib/auth.py
- src/resources/lib/client.py
- src/resources/lib/modeling.py
- src/resources/lib/utils.py
> Added support of python 3.6

- src/resources/lib/settings.py
> Added support of profiles in advanced settings

- src/resources/lib/modeling.py
Если я ничего не напутал, это должно пофиксить проблему. Протестировал с Kodi 19:
> A Show name is shown instead of an Episode name

- src/resources/lib/listitem.py
- src/resources/lib/modeling.py
> Return missing context menu item

- src/addon.xml
- src/resources/language/resource.language.en_gb/strings.po
- src/resources/language/resource.language.ru_ru/strings.po
- src/resources/language/resource.language.uk_ua/strings.po
- src/resources/lib/auth.py
- src/resources/lib/client.py
- src/resources/lib/listitem.py
- src/resources/lib/main.py
- src/resources/lib/modeling.py
- src/resources/lib/plugin.py
- src/resources/lib/settings.py
- src/resources/lib/utils.py
- src/resources/settings.xml
- tests/expected_results.py
- tests/test_unit.py
Added localization for English, Russian and Ukrainian languages.
> Localization

- src/resources/lib/plugin.py
> Fix settings attribute for inputstream adaptive

- src/resources/language/resource.language.en_gb/strings.po
- src/resources/language/resource.language.ru_ru/strings.po
- src/resources/language/resource.language.uk_ua/strings.po
- src/resources/lib/main.py
- src/resources/settings.xml
> Add InputStream Adaptive settings

- src/resources/lib/main.py
Fixes https://github.com/quarckster/kodi.kino.pub/issues/377
> "Profile" menu action is broken #377
